### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by vischulisem** [pardojer23/RNAseqV2#2]
I am getting this error after running 'python setup.py install --user'

error: The 'backports.zoneinfo; python_version < "3.9"' distribution was not found and is required by tzlocal

I am running this on HPCC in conda environment.

<img width="1601" alt="Screen Shot 2020-11-02 at 12 31 37 PM" src="https://user-images.githubusercontent.com/52712211/97899493-5ef4a500-1d07-11eb-95d4-bebb30a376dc.png">

**Comment by pardojer23** [comment]
I don't think this is an error in the pipeline as I'm not able to replicate your issue. I suspect that since you are running it on the computing cluster the system admin may have a version of python installed and if you try using that you'll get an error because your user account doesn't have permission to install any software. If you haven't already install Anaconda or miniconda in your home folder. With the base environment active (you should see (base) pre-pended to your prompt) try running `which python` it should return something like `~/miniconda3/bin/python`. If not, try running `module purge` to unload any modules from the computing cluster before running `python setup.py` install. Also if you have previous failed installations try removing those first.
